# Generated by Django 5.0.7 on 2024-07-16 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('can_delete_any_comment', 'Can delete any comment')]},
        ),
    ]
