# Generated by Django 5.0.7 on 2024-07-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(default='Default content'),
            preserve_default=False,
        ),
    ]
