# Generated by Django 5.0.7 on 2024-08-07 22:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_notification_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='body',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['subcategory', 'author'], name='accounts_to_subcate_54e125_idx'),
        ),
    ]
